version: '2.1'

services:
  economy:
    container_name: economy
    hostname: economy
    restart: always
    build: economy
    networks:
      tsworker-net:docker-compose-3.yml
    expose:
      - "8000"
    volumes:
      - ./data:/tmp/data:ro
    command: gunicorn -w 1 -b :8000 economy:server

  elections:
    container_name: elections
    hostname: elections
    restart: always
    build: elections
    networks:
      tsworker-net:
    expose:
      - "8500"
    volumes:
      - ./data:/tmp/data:ro
      - ./assets:/tmp/assets:ro
    environment:
      - FLASK_ENV=development
    command: gunicorn --log-level debug -w 1 -b :8500 elections:server

  social:
    container_name: social
    hostname: social
    restart: always
    build: social
    networks:
      tsworker-net:
    expose:
    - "9000"
    volumes:
      - ./data:/tmp/data:ro
    command: gunicorn -w 1 -b :9000 social:server # was 8000

  nginx:
    image: nginx:1.15
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      tsworker-net:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.http.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/etc:/etc/letsencrypt
      - /etc/letsencrypt/www:/var/www/letsencrypt
    environment:
      - TZ=UTC
    depends_on:
      - economy
      - elections
      - social

networks:
  tsworker-net:
    driver: bridge
